### ISSUE TITLE
the ranger buffer has too many unnecessary UI elements enabled

### ISSUE THREAD

**Issue by alezunino** [kelly-lin/ranger.nvim#1]
When opening a ranger window, it uses the default nvim UI elements (ruler, statusbar, etc) that are not necessary in ranger. This can be easily fixed by using the "minimal" style when creating the ranger window with [vim.api.nvim_open_win](https://neovim.io/doc/user/api.html#nvim_open_win()). The following patch solves this minor issue:
[winStyle.txt](https://github.com/kelly-lin/ranger.nvim/files/11405007/winStyle.txt)

**Comment by kelly-lin** [comment]
Thanks @alezunino, I have made the changes and pushed them.
