### ISSUE TITLE
Can preview image like ranger in Shell?

### ISSUE THREAD

**Issue by guxuerui** [kelly-lin/ranger.nvim#10]
Hello, can I preview image by`ranger.nvim`? Just like use ranger in Shell, for example this below,  and what should I config?

![image](https://github.com/kelly-lin/ranger.nvim/assets/23629097/1c57677c-1104-4195-a5d6-0d99eb5d07b9)

**Comment by kelly-lin** [comment]
Hey @guxuerui,

`ranger.nvim` *should* display exactly the same thing as running `ranger` in the command line without any configuration required.

Is `ranger.nvim` displaying something different to `ranger`? If it is, do you mind sharing a screenshot?

**Comment by guxuerui** [comment]
> Hey @guxuerui,
> 
> `ranger.nvim` _should_ display exactly the same thing as running `ranger` in the command line without any configuration.
> 
> Is `ranger.nvim` displaying something different to `ranger`? If it is, do you mind sharing a screenshot?

Yes, I can preview image use `ranger` in command line, but cant't in `ranger.nvim`.

I'm using `Iterm2`, my `nvim` version is `0.9.0` and my `ranger.nvim` configuation is :

```lua
return {
	{
		"kelly-lin/ranger.nvim",
		config = function()
			require("ranger-nvim").setup({
				enable_cmds = true,
				replace_netrw = true,
				ui = {
					border = "rounded",
					width = 0.6,
					height = 0.6,
				},
			})
			vim.api.nvim_set_keymap("n", "<leader>er", "", {
				noremap = true,
				callback = function()
					require("ranger-nvim").open(true)
				end,
			})
		end,
	},
}
```

**Screenshot:**
![image](https://github.com/kelly-lin/ranger.nvim/assets/23629097/89c7f380-61b6-47a0-9aad-2d0d7a1156d4)

**Comment by kelly-lin** [comment]
@guxuerui are you using something like [ueberzug](https://github.com/seebye/ueberzug) underneath iterm2 to view the images? Or is images supported directly through iterm2?

**Comment by guxuerui** [comment]
> @guxuerui are you using something like [ueberzug](https://github.com/seebye/ueberzug) underneath iterm2 to view the images? Or is images supported directly through iterm2?

Directly through iterm2 and ranger. 

In ranger configuration, I have set `preview_images` to true, and I can also see that when I view the settings in `ranger.nvim`.

So, I am quite puzzled, could it be that I am missing some `ranger.nvim` configurations which are causing the inability to preview images?

**Comment by guxuerui** [comment]
> > @guxuerui are you using something like [ueberzug](https://github.com/seebye/ueberzug) underneath iterm2 to view the images? Or is images supported directly through iterm2?
> 
> Directly through iterm2 and ranger. 
> 
> In ranger configuration, I have set `preview_images` to true, and I can also see that when I view the settings in `ranger.nvim`.
> 
> So, I am quite puzzled, could it be that I am missing some `ranger.nvim` configurations which are causing the inability to preview images?

Or, is it because image preview is not supported in Neovim itself?

**Comment by kelly-lin** [comment]
> > > @guxuerui are you using something like [ueberzug](https://github.com/seebye/ueberzug) underneath iterm2 to view the images? Or is images supported directly through iterm2?
> > 
> > 
> > Directly through iterm2 and ranger.
> > In ranger configuration, I have set `preview_images` to true, and I can also see that when I view the settings in `ranger.nvim`.
> > So, I am quite puzzled, could it be that I am missing some `ranger.nvim` configurations which are causing the inability to preview images?
> 
> Or, is it because image preview is not supported in Neovim itself?

It is possible.

What happens when you run `ranger` from an integrated terminal from neovim (follow the steps below)?
- Run the command `:terminal` (it should start a new integrated terminal in neovim)
- Enter insert mode `i`.
- Type in `ranger` and press `enter`.
- Focus on an image
- What is shown on preview?

**Comment by guxuerui** [comment]
> 

I followed these steps, but I still can't preview the image. 
Maybe I should give up on this feature😂. Thank you for your help!

**Comment by ariel-frischer** [comment]
I'm seeing the same issue, using kitty terminal w/ pillow I guess for image previews. I see previews from console ranger but not from neovim ranger, using integrated `:terminal` the previews don't work either. Why was this closed?

**Comment by exosyphon** [comment]
I am also not seeing the image previews

**Comment by guxuerui** [comment]
> I'm seeing the same issue, using kitty terminal w/ pillow I guess for image previews. I see previews from console ranger but not from neovim ranger, using integrated `:terminal` the previews don't work either. Why was this closed?

Sorry, because I tried many methods but couldn't solve the problem, I gave up using this feature and eventually closed this issue.
