### ISSUE TITLE
Binding <C-s> freezes terminal

### ISSUE THREAD

**Issue by abenz1267** [kelly-lin/ranger.nvim#12]
Hi,

thanks for the plugin.

I tried binding `<C-s>` to OPEN_MODE.split, but it crashes my terminal. Any idea why?

Regards

**Comment by kelly-lin** [comment]
Hey @abenz1267, do you mind sharing your `ranger.setup()` table?

**Comment by abenz1267** [comment]
```
        ranger.setup({
            replace_netrw = true,
            ui = {
                height = 0.90,
                y = 0
            },
            keybinds = {
                ['<C-v>'] = ranger.OPEN_MODE.vsplit,
                ['<C-r>'] = ranger.OPEN_MODE.split,
                ['<C-t>'] = ranger.OPEN_MODE.tabedit,
            }
        })
```

**Comment by kelly-lin** [comment]
@abenz1267 it looks like we cannot override the ranger default binding for `<C-s>` which freezes the output. If you press `<C-s>` in ranger (not in `ranger.nvim`) you will see that the behaviour is consistent. See [this issue](https://github.com/ranger/ranger/issues/982).

**Comment by abenz1267** [comment]
Aaahhhh, interesting. I wasn't even aware of such functionality.

**Comment by marcelarie** [comment]
So what is the solution to bind C-s to open split windows in ranger.nvim?
