### ISSUE TITLE
Seeing the command in the statusline.

### ISSUE THREAD

**Issue by sh-cau** [kelly-lin/ranger.nvim#16]
Usually, when I open a terminal and press, e.g., ":mkdir test" or ":touch test.py", I see this in the window below. But when I use this plugin, I don't see anything that I type. This may also relate to the fact, that my color scheme does not seem to be loaded?
Left image: "normal" ranger.
Right image: ranger startet from nvim.
<p align="middle">
     <img src="https://github.com/kelly-lin/ranger.nvim/assets/27808377/df41546e-903a-4619-966e-78edb05c2e71"/ width=400> 
     <img src="https://github.com/kelly-lin/ranger.nvim/assets/27808377/455820e6-1285-4bab-b181-a7111cf9292a"/ width=400> 
</p>

I am using Lazy as a package manager. I use Neovim v0.9.1.

**Comment by FelipeAfonso** [comment]
Try changing the height to 0.95 in the UI config. Looks like your nvim status line is in the way.

**Comment by sh-cau** [comment]
That did the trick. Wouldn't have thought of that. Thanks

**Comment by make-github-pseudonymous-again** [comment]
Is there a way to draw this on top of the status line? Or disable the status line for the buffer `ranger` is drawn on? I am using `mini.statusline`, and their seem to be a way to disable it for specific buffers: https://github.com/echasnovski/mini.nvim/blob/71b5694a2df4f7e3661855eb8e2814980d2e0ac9/lua/mini/statusline.lua#L72-L76.
