### ISSUE TITLE
Suggestion to include a neovim command

### ISSUE THREAD

**Issue by dPenedo** [kelly-lin/ranger.nvim#3]
Hi! First of all I want a thank you for the plugin, it's working perfectly and it fits my needs of a simple integration of ranger in neovim, perfectly. Without dependencies and so on. Very cool!!

I wanted to suggest to add a neovim command. I wasn't needing it, because the keymap that you provided works perfectly, but it was a little hacky to integrate it with Alpha.nvim. So I made this line to make ":Ranger" a command to add it:
```
vim.cmd('command! Ranger lua require("ranger-nvim").open(true)')
```
Thank you for your time!

**Comment by kelly-lin** [comment]
Hi, @dPenedo! Thank for you for your suggestion and I am happy to add in a vim command to the plugin.

For my benefit, why is it hacky to integrate with Alpha.nvim?

**Comment by dPenedo** [comment]
That's great!! 
About how I integrated it with Alpha, It wasn't a big deal, maybe "hacky" wasn't the best word but verbose, the rest of init actions where looking like this:
```
     dashboard.button("l", "󰒲 " .. " Lazy", ":Lazy<CR>"),

```
And I achieved that with ranger.nvim like this:
```
            dashboard.button("r", "📂 " .. "Ranger", ":lua require(\"ranger-nvim\").open(true) <CR>"),
```
Now, witrh the vim command looks like this:
```
            dashboard.button("r", "📂 " .. "Ranger", ":Ranger <CR>"),
```

Not a big deal anyway!

**Comment by kelly-lin** [comment]
Hey @dPenedo ,

Just added this feature in [923593d](https://github.com/kelly-lin/ranger.nvim/commit/923593d0f02d8d8e320c7b961dd068c19bc0ced9). I have disabled it by default, so to enable them you will have configure it via the setup function. I have updated the readme to reflect the new flag.
