### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by I-Own-You** [kelly-lin/ranger.nvim#4]
Hi, its a nice integration of ranger into neovim. 
Right now, when you enter ranger from neovim, the keymaps defined in neovim still persists in ranger, and it results in a lot of *delays* and *misstypings*.
For example:
 <ul> <li>i have mapped spacebar to a lot of letters and spacebar is toggling aswell in ranger, but it toggles with a delay.
<li>  and so on with others keymaps. 
</ul>

Could you make it possible to disable all the keymaps from neovim while being in *ranger* mode ?
It could be a property in setup() function like *disable_neovim_keymaps = true*

**Comment by kelly-lin** [comment]
Hi @I-Own-You, thank you, I hope the plugin is serving you well.

To clarify, are you referring to the ranger bindings that the plugin sets for ranger when the plugin launches ranger inside neovim? i.e. the default bindings `ot` for open in new tab and `ov` for open in vertical split?

Or are you referring to the bindings (I am guessing they are terminal bindings?) you have set in your neovim config which are also triggering in the ranger window inside neovim when it launches?

**Comment by I-Own-You** [comment]
> Hi @I-Own-You, thank you, I hope the plugin is serving you well.
> 
> To clarify, are you referring to the ranger bindings that the plugin sets for ranger when the plugin launches ranger inside neovim? i.e. the default bindings `ot` for open in new tab and `ov` for open in vertical split?
> 
> Or are you referring to the bindings (I am guessing they are terminal bindings?) you have set in your neovim config which are also triggering in the ranger window inside neovim when it launches?

At least can you make j and k to not have an input delay ? like this plugin [rnvimr](https://github.com/kevinhwang91/rnvimr). 
Here in the issues he solves it like this: https://github.com/kevinhwang91/rnvimr/issues/66#issuecomment-841610792
Something like setting a custom filetype like he did so i could map j and k to not have a delay ? your plugin is in lua and it is very fast, it would be nice
